---

is_debug: true
listen:
  type: port
  bind_ip: localhost
  port: 9090
timeout:
  write: 15
  read: 15
mongodb:
  host: db
  port: 27017
  database: MongoDB
  authdb:
  username:
  password:
  collection: users