// Creating user http request example
POST http://localhost:8080/create
Content-Type: application/json

{"username": "Vitaliy", "age":"25", "friends": ["Masha", "Miron"]}

###

// Creating user http request example
POST http://localhost:8080/create
Content-Type: application/json

{"username": "Vasya", "age":"25", "friends": ["Masha", "Miron"]}

###

// Getting friends from one user http request example
GET  http://localhost:8080/friends/61c774d59ea656672ede6dfd
Content-Type: application/json

###

// Change age of one user http request example
PUT http://localhost:8080/users/61dc52d149f08d61c25a8172
Content-Type: application/json

{"age": "43"}

###

// Making friends two users http request example
POST http://localhost:8080/make_friends
Content-Type: application/json

{"source_id": "61dc52d149f08d61c25a8171",  "target_id":"61dc52d149f08d61c25a8172"}

###

// Delete user http request example
DELETE http://localhost:8080/users/
Content-Type: application/json

{"target_id": "61dc52d149f08d61c25a8172"}
