---

is_debug: true
listen:
  type: port
  bind_ip: 127.0.0.1
  port: 8080
timeout:
  write: 15
  read: 15
mongodb:
  host: localhost
  port: 27017
  database: MongoDB
  authdb:
  username:
  password:
  collection: users